
@startuml "WP3-scope.png"
scale 0.6
!define SHOW_Management

!define SHOW_IdentityManagement
!define SHOW_Repository
!define SHOW_Registry

!define SHOW_Runtime

!define SHOW_UA_A
!define SHOW_EndUserA

!define SHOW_NetServ
!define SHOW_NetDevice

!define SHOW_MsgServer

!define SHOW_NQC

!include CoreArchElements.plantuml



Bus -up-> ManI

MsgI -up- Bus

ManI -up- Reg: Manage Hyperty

ManI -up- Rep
ManI -up- IdM

Alice -[hidden]right-> Net

Alice <-up-> MsgI

Net <-up-> MsgI

Alice -down- StreamI

Net -down- StreamI

NQC -up- StreamI  

Alice ...[hidden]right- Net

MsgI <-down-> NQC


@enduml
