@startuml user-to-hyperty-binding-scheme.png

autonumber
actor Alice #red
box "Alice's Device Core Runtime" #LightGrey
participant RuntimeUA
participant Registry
participant IdModule
participant PolicyEngine
end box
box "Service Provider 1 Sandbox at Alice Device" #LightGrey

== Associate hyperty instance with user identity ==

RuntimeUA -> IdModule : getIdentities

RuntimeUA <- IdModule : Identities returned

opt Policy Enforcer is requested\n to authorise ID Selection

PolicyEngine <- RuntimeUA: authoriseIDHypertyBind\n(Identities)

PolicyEngine <- PolicyEngine: apply policies

alt IdModule has more than one Identity\nloaded and user has to select one.

Alice <- PolicyEngine: request to select Identity

Alice -> PolicyEngine: return selected Identity

end

PolicyEngine -> RuntimeUA: return authorised Identity

end

RuntimeUA -> IdModule: getIDToken(Identifier, scope)

RuntimeUA <- IdModule: ID Token returned

RuntimeUA -> Registry : bindIdentity(HypertyURL, IDToken)

end box


@enduml
